// File generated by Antigravity using google-services.json metadata.
// Do not edit.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQfJnq8Jrox4CpgkbBV1W3DBY53fNh1F0',
    appId: '1:941694628145:web:03a0c859c1e1a92dee0010',
    messagingSenderId: '941694628145',
    projectId: 'promo-1000',
    authDomain: 'promo-1000.firebaseapp.com',
    storageBucket: 'promo-1000.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQfJnq8Jrox4CpgkbBV1W3DBY53fNh1F0',
    appId: '1:941694628145:android:03a0c859c1e1a92dee0010',
    messagingSenderId: '941694628145',
    projectId: 'promo-1000',
    storageBucket: 'promo-1000.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQfJnq8Jrox4CpgkbBV1W3DBY53fNh1F0',
    appId: '1:941694628145:ios:03a0c859c1e1a92dee0010',
    messagingSenderId: '941694628145',
    projectId: 'promo-1000',
    storageBucket: 'promo-1000.firebasestorage.app',
    iosBundleId: 'com.brand.brandMobileApp',
  );
}
